spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/moja_baza
spring.datasource.username=postgres
spring.datasource.password=gabrynia
spring.jpa.hibernate.ddl-auto=update